01_skeleton/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('profile/<int:user_pk>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

01_skeleton/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:movie_pk>/likes/', views.likes, name='likes'),
]

01_skeleton/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

01_skeleton/movies/models.py
from django.db import models
from django.conf import settings


class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    title = models.CharField(max_length=20)
    description = models.TextField()

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.content

01_skeleton/movies/forms.py
from django import forms
from .models import Movie, Comment


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = (
            'user',
            'movie',
        )

01_skeleton/movies/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth.decorators import login_required
from .models import Movie, Comment
from .forms import MovieForm, CommentForm


@require_GET
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)


@require_GET
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        'movie': movie,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'movies/detail.html', context)


@require_POST
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/update.html', context)


def comments_create(request, pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.movie = movie
        comment.user = request.user
        comment.save()
    return redirect('movies:detail', movie.pk)


def comments_delete(request, pk, comment_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('movies:detail', pk)

@require_POST
def likes(request, movie_pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=movie_pk)
        if movie.like_users.filter(pk=request.user.pk).exists():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect('movies:index')
    return redirect('accounts:login')

01_skeleton/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <hr>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:index' %}">BACK</a>
{% endblock %}

01_skeleton/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <hr>
  <div>
    <h5>{{ movie.title }}</h5>
    <br>
    <p>{{ movie.description }}</p>
  </div>

  {% if request.user == movie.user %}
      <a href="{% url 'movies:update' movie.pk %}">UPDATE</a>
      <form action="{% url 'movies:delete' movie.pk %}" method="POST" id="delete-form">
        {% csrf_token %}
        <input type="submit" value="DELETE" id="delete-btn" />
      </form>
  {% endif %}
  <a href="{% url 'movies:index' %}">BACK</a>
  <hr>

  <h5>댓글목록</h5>
    {% if comments %}
      <p><b>{{comments|length}}개의 댓글</b></p>
    {% endif %}

    <ul>
      {% for comment in comments %}
        <li>
          {{comment.content}} - {{comment.user}}
          {% if request.user == comment.user %}
            <form action="{% url 'movies:comments_delete' movie.pk comment.pk%}" method="POST">
              {% csrf_token %}
              <input type="submit" value="삭제">
            </form>
          {% endif %}
        </li>
      {% empty %}
        <li>댓글이 없습니다 :</li>
      {% endfor %}
    </ul>
    
    {% if request.user.is_authenticated %}
      <form action="{% url 'movies:comments_create' movie.pk %}" method="POST">
        {% csrf_token %}
        {{comment_form}}
        <input type="submit" value="저장">
      </form>
    {% else %}
      <a href="{% url 'accounts:login' %}">댓글 달려면 로그인 하라구!</a>
    {% endif %}
  <hr>
{% endblock  %}

01_skeleton/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'movies:create' %}">[CREATE]</a>
  <hr>
  {% for movie in movies %}
    <p>
      [{{movie.id}}] 
      <a href="{% url 'movies:detail' movie.pk %}" id="movie-title">{{movie.title}}</a>
      
    </p>

    <p><b>{{movie.like_users.all|length}}개의 좋아요</b></p>

    {% if request.user.is_authenticated %}
      <div>
        <form action="{% url 'movies:likes' movie.pk %}" method="POST">
          {% csrf_token %}
          {% if request.user in movie.like_users.all %}
            <input type="submit" value="안좋아해!">
          {% else %}
            <input type="submit" value="좋아해!">
          {% endif %}
        </form>
      </div>
    {% endif %}
    <hr />
  {% endfor %}
{% endblock %}

01_skeleton/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <hr>
  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">TITLE</label>
      <input type="text" id="title" name="title" value="{{ movie.title }}">
    </div>
    <div>
      <label for="description">DESCRIPTION</label>
      <textarea id="description" rows="3" name="description">{{ movie.description }}</textarea>
    </div>
    <input type="reset" value="Reset">
    <button type="submit">Submit</button>
  </form>
  <hr>
  <a href="{% url 'movies:detail' movie.pk %}">BACK</a>
{% endblock %}